export const mockData = {
  stats: {
    pessoasDentro: 247,
    veiculosDentro: 18,
    entradasHoje: 89,
    saidasHoje: 76,
  },
  registros: [
    {
      id: 1,
      tipo: "entrada",
      categoria: "pessoa",
      nome: "Sgt. João Silva",
      posto: "Sargento",
      unidade: "1ª Cia",
      documento: "123.456.789-00",
      horario: "08:30",
      data: "2024-01-15",
      veiculo: null,
    },
    {
      id: 2,
      tipo: "saida",
      categoria: "veiculo",
      nome: "Cb. Maria Santos",
      posto: "Cabo",
      unidade: "2ª Cia",
      documento: "987.654.321-00",
      horario: "09:15",
      data: "2024-01-15",
      veiculo: {
        id: 1,
        placa: "ABC-1234",
        tipo: "Viatura",
        modelo: "Toyota Hilux",
      },
    },
    {
      id: 3,
      tipo: "entrada",
      categoria: "pessoa",
      nome: "Ten. Carlos Oliveira",
      posto: "Tenente",
      unidade: "Estado Maior",
      documento: "456.789.123-00",
      horario: "07:45",
      data: "2024-01-15",
      veiculo: null,
    },
    {
      id: 4,
      tipo: "entrada",
      categoria: "veiculo",
      nome: "Sd. Ana Costa",
      posto: "Soldado",
      unidade: "3ª Cia",
      documento: "195115",
      horario: "10:20",
      data: "2024-01-15",
      veiculo: {
        placa: "XYZ-5678",
        tipo: "Particular",
        modelo: "Honda Civic",
      },
    },
    {
      id: 5,
      tipo: "saida",
      categoria: "pessoa",
      nome: "Cap. Roberto Lima",
      posto: "Capitão",
      unidade: "1ª Cia",
      documento: "321.654.987-00",
      horario: "11:00",
      data: "2024-01-15",
      veiculo: null,
    },
  ],

  pessoa: [
    {
      id: 1,
      name: "João Silva",
      documento: "123456",
      posto: "1º Sargento",
      unidade: "1ª Cia",
      veiculo: null, //ou id do veiculo
      createdAt: "",
      updatedAt: ""
    },
  ],
  veiculos: [
    {
      id: 1,
      placa: "AAA-1234",
      tipo: "Particular",
      modelo: "Corola",
      cartão: "1234",
      pessoaID: "",
      createdAt: "",
      updatedAt: "",
    },
  ],
}

